algorithm: nsclccox_fusion_dual
save_dir: ./saved_models/usb_ns/
save_name: nsclccox_ilthctn
resume: True
load_path: ./saved_models/usb_ns/nsclccox_ilthctn_0/model_best_1.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 112
num_train_iter: 9520
num_log_iter: 10
num_eval_iter: 17
batch_size: 4
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 84
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
dist_align: True
dist_uniform: True
per_class: False
ema_p: 0.999
ulb_loss_ratio: 1.0
model_loss_ratio: 1.0
n_sigma: 2
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
t_weak_intensity: 0.1
t_strong_intensity: 1
net: dualnet_3Dimg_6in1
prompt_split: False
fusing: True
freeze_backbone: True
net_from_name: False
data_dir: ./data/NSCLC
train_sampler: RandomSampler
target_type: time
num_classes: 150
slides_num: 20
split_id: 0
ulb_rate: 0.8
surv_loss: nll
sampler_weights: 1,4
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10086
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path_vit: ./saved_models/usb_ns/semi-fusion-cox-mona/model_best.pth
pretrain_path_finetune: ./saved_models/usb_ns/semi-fusion-cox-finetune/model_best.pth
