algorithm: nsclccox_fusion
save_dir: ./saved_models/usb_ns/
save_name: semi-fusion-cox-mona
resume: True
load_path: ./saved_models/usb_ns//semi-fr_classify.yaml/model_best.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 595
num_train_iter: 4760
num_log_iter: 10
num_eval_iter: 68
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 84
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
dist_align: True
dist_uniform: True
per_class: False
ema_p: 0.999
ulb_loss_ratio: 1.0
n_sigma: 2
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: monet_3Dimg_6in1
prompt_split: False
fusing: False
freeze_backbone: True
net_from_name: False
data_dir: ./data/NSCLC
train_sampler: RandomSampler
target_type: time
num_classes: 150
ulb_rate: 0.8
slides_num: 20
split_id: 0
surv_loss: nll
sampler_weights: 1.25,4.996
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10086
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch16_224_mlp_im_1k_224.pth