algorithm: refixmatch_cox
save_dir: ./saved_models/usb_cv/
save_name: refixmatch-fracture-cox
resume: True
load_path: ./saved_models/usb_cv/refixmatch-fracture-cox/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 1000
num_train_iter: 119000
num_log_iter: 100
num_eval_iter: 119
batch_size: 16
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 84
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 5e-05
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
net: vit_small_patch16_224
fusing: False
freeze_backbone: False
net_from_name: False
data_dir: ./data/fracture
train_sampler: RandomSampler
split_id: 1
target_type: fracTime
num_classes: 91
surv_loss: nll
sampler_weights: 1.25,4.996
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch16_224_mlp_im_1k_224.pth
use_wandb: False
