algorithm: softmatch_fusion
save_dir: ./saved_models/usb_fu/
save_name: semi-fusion
resume: True
load_path: ./saved_models/usb_fu//semi-fusion.yaml/model_best.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 2000
num_train_iter: 238000
num_log_iter: 200
num_eval_iter: 595
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 84
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
dist_align: True
dist_uniform: True
per_class: False
ema_p: 0.999
ulb_loss_ratio: 1.0
n_sigma: 2
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: funet_1img_52in1
prompt_split: False
fusing: True
freeze_backbone: True
net_from_name: False
data_dir: E:/Project/dataset
train_sampler: WeightedRandomSampler
split_id: 0
target_type: ifMOF
num_classes: 2
sampler_weights: 1.25,4.996
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10086
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: ./saved_models/usb_fu/semi-fr_classify/74_img_only_0_weight_0.816-0.726/model_best.pth
pretrained_from: MyNet